use_frameworks!

platform :ios, '8.0'

target 'PopUpAlertManager_Example' do
  pod 'PopUpAlertManager', :path => '../'

  target 'PopUpAlertManager_Tests' do
    inherit! :search_paths

    
  end
end
